name: Tests

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 */3 * * *' # Every 3 hours

env:
  FMP_REPOSITORY: https://github.com/fabric8io/fabric8-maven-plugin.git
  FMP_REVISION: master

jobs:
  minikube:
    name: Generic Test using Minikube
    runs-on: ubuntu-latest
    strategy:
      matrix:
        minikube: [v1.5.1]
        kubernetes: [v1.16.2,v1.12.0]
    env:
      MINIKUBE_URL: https://github.com/kubernetes/minikube/releases/download/${{ matrix.minikube }}/minikube-linux-amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download latest Docker Version
        run: |
          sudo apt-get purge docker docker-engine docker.io containerd runc \
          && sudo rm -rf /var/lib/docker \
          && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - \
          && sudo add-apt-repository \
                "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) \
                stable" \
          && sudo apt-get update \
          && sudo apt-get install docker-ce docker-ce-cli
      - name: Download minikube
        run: curl -Lo minikube "$MINIKUBE_URL" && chmod +x minikube
      - name: Start minikube
        run: |
          sudo -E ./minikube start --vm-driver=none --kubernetes-version ${{ matrix.kubernetes }} \
          && sudo chmod -R a+r /home/runner/.kube /home/runner/.minikube
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Checkout fabric8-maven-plugin
        run: |
          git clone "$FMP_REPOSITORY" \
          && cd ./fabric8-maven-plugin \
          && git  checkout "$FMP_REVISION" \
          && cd ..
      - name: Install fabric8-maven-plugin SNAPSHOT
        run: mvn -f ./fabric8-maven-plugin -B -DskipTests clean install
      - name: Install and Run Integration Tests
        run: ./mvnw -B -PKubernetes clean verify
      - name: Consolidate reports
        run: |
          mkdir -p ./reports/zero-config/spring-boot \
          && cp -R ./it/target/failsafe-reports ./reports \
          && cp -R ./zero-config/spring-boot/target/docker ./reports/zero-config/spring-boot \
          && cp -R ./zero-config/spring-boot/target/classes/META-INF ./reports/zero-config/spring-boot
      - name: Save reports as artifact
        uses: actions/upload-artifact@master
        with:
          name: Test reports
          path: ./reports
  openshift:
    name: Generic Test using OpenShift Cluster
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openshift: [v3.11.0,v3.9.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.0.1
        with:
          oc version: ${{ matrix.openshift }}
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Checkout fabric8-maven-plugin
        run: |
          git clone "$FMP_REPOSITORY" \
          && cd ./fabric8-maven-plugin \
          && git checkout "$FMP_REVISION" \
          && cd ..
      - name: Install fabric8-maven-plugin SNAPSHOT
        run: mvn -f ./fabric8-maven-plugin -B -DskipTests clean install
      - name: Install and Run Integration Tests
        run: ./mvnw -B -POpenShift clean verify




