name: Tests

on: push

env:
  FMP_REPOSITORY: https://github.com/fabric8io/fabric8-maven-plugin.git
  MINIKUBE_URL: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64

jobs:
  generic-test:
    name: Generic Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Checkout fabric8-maven-plugin
        run: git clone "$FMP_REPOSITORY"
#      - name: Install fabric8-maven-plugin SNAPSHOT
#        run: mvn -f ./fabric8-maven-plugin -B -DskipTests clean install
#      - name: Cache Maven Dependencies
#        uses: actions/upload-artifact@master
#        with:
#          name: maven-dependencies
#          path: /home/runner/.m2
      - name: Download latest Docker Version
        run: |
          sudo apt-get purge docker docker-engine docker.io containerd runc \
          && sudo rm -rf /var/lib/docker \
          && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - \
          && sudo add-apt-repository \
                "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) \
                stable" \
          && sudo apt-get update \
          && sudo apt-get install docker-ce docker-ce-cli
      - name: Download minikube
        run: curl -Lo minikube "$MINIKUBE_URL" && chmod +x minikube
      - name: Start minikube
        run: sudo -E ./minikube start --vm-driver=none


