name: Tests

on: push

env:
  JAVA_VERSION: 11
  FMP_REPOSITORY: https://github.com/fabric8io/fabric8-maven-plugin.git


jobs:
  generic-test:
    name: Generic Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: "$JAVA_VERSION"
      - name: Checkout fabric8-maven-plugin
        run: git clone "$FMP_REPOSITORY"


