name: Tests

on: push

env:
  FMP_REPOSITORY: https://github.com/fabric8io/fabric8-maven-plugin.git

jobs:
  generic-test:
    name: Generic Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Checkout fabric8-maven-plugin
        run: git clone "$FMP_REPOSITORY"
      - name: Install fabric8-maven-plugin snapshot
        run: mvn -f ./fabric8-maven-plugin -B -Pjavaall -DskipTests clean install


